# Project Configuration

language: c

sudo: required

services:
  - docker

before_install:
  - docker pull ja3067/coral-build

script:
  - docker run -u 0 -v $(pwd):/data -w /data --rm -t ja3067/coral-build make test
